prestop_node:
  ros__parameters:
    cmd_vel_in_topic: "/cmd_vel_raw"
    cmd_vel_out_topic: "/cmd_vel"
    scan_in_topic: "/low_scan_raw"
    scan_out_topic: "/low_scan"

    empty_scan_mode: "inf"
    base_frame_id: "base_link"
    visualize_stop_zone: true
    stop_zone_polygon_topic: "/prestop/stop_zone_polygon"
    stop_duration: 3.0

    polygons:
      stop_zone:
        enabled: true
        action_type: "stop"
        points: "[[0.3, 0.4], [1.2, 0.4], [1.2, -0.4], [0.3, -0.4]]"
